@startuml
!include style.puml
skinparam classAttributeIconSize 0
skinparam classAttributeFontColor #FFFFFF
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeFontSize 18
show members
hide empty members

Class Person {
    -isArchived : Boolean
    -isStarred : Boolean
}

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" MeetingNote
Person *--> InsurancePolicy
Person -right> "*" Reminder
@enduml
